version: '3.8'

services:

  bot:
    restart: always
    build: spam-telegram-bot
    ports:
      - "5000:5000"

  php:
    restart: always
    build: php-spam-bot-service
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "sleep 5 && ./vendor/bin/doctrine-migrations migrate --no-interaction && php -S 0.0.0.0:8000 public/index.php"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  db_data:
